"""Track-level labeling tool for ground truth collection.

Usage:
    streamlit run scripts/label_tracks.py -- \
        --predictions output/predictions.csv \
        --video data/sample.mp4 \
        --out labels/ground_truth.csv

Workflow:
  1. Loads predictions.csv (generated by pipeline with save_predictions: true)
  2. Extracts one representative crop per tracker_id from the video
  3. Renders a grid: crop image + model's predicted label pre-filled
  4. Human only corrects wrong labels (fast — most will already be correct)
  5. "Save Labels" exports labels/ground_truth.csv (tracker_id, true_label)
"""

import argparse
import os
import sys
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import streamlit as st

LABELS = ["team_a", "team_b", "other"]
DEFAULT_PREDICTIONS = "output/predictions.csv"
DEFAULT_VIDEO = "data/sample.mp4"
DEFAULT_OUT = "labels/ground_truth.csv"

st.set_page_config(page_title="Soccer Vision — Label Tracks", layout="wide")


# ---------------------------------------------------------------------------
# Argument parsing (streamlit passes extra args after --)
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--predictions", default=DEFAULT_PREDICTIONS)
    parser.add_argument("--video", default=DEFAULT_VIDEO)
    parser.add_argument("--out", default=DEFAULT_OUT)
    # streamlit injects its own argv; grab only what's after '--'
    argv = sys.argv[1:]
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        argv = []
    return parser.parse_args(argv)


args = _parse_args()


# ---------------------------------------------------------------------------
# Data loading helpers
# ---------------------------------------------------------------------------

@st.cache_data(show_spinner="Loading predictions…")
def load_predictions(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {"frame_idx", "tracker_id", "x1", "y1", "x2", "y2", "predicted_label"}
    missing = required - set(df.columns)
    if missing:
        st.error(f"predictions.csv is missing columns: {missing}")
        st.stop()
    return df


@st.cache_data(show_spinner="Extracting track crops…")
def extract_crops(predictions_path: str, video_path: str, crop_size: int = 96) -> dict:
    """Return dict[tracker_id] = (RGB uint8 crop, predicted_label, frame_idx)."""
    df = load_predictions(predictions_path)

    # Pick the median frame per track — most temporally stable crop
    track_rows = {}
    for tid, group in df.groupby("tracker_id"):
        group = group.sort_values("frame_idx").reset_index(drop=True)
        mid_idx = len(group) // 2
        row = group.iloc[mid_idx]
        track_rows[int(tid)] = row

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        st.error(f"Cannot open video: {video_path}")
        st.stop()

    # The pipeline auto-downscales to MAX_RESOLUTION (1080px wide), so bbox
    # coordinates in predictions.csv are in pipeline-space, not original-video
    # space.  Derive the scale factor from the original video dimensions so we
    # can downscale each frame to the same size before cropping.
    orig_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    orig_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    MAX_RESOLUTION = 1080  # must match utils/video_io.py MAX_RESOLUTION
    if orig_w > MAX_RESOLUTION:
        scale = MAX_RESOLUTION / orig_w
        proc_w = MAX_RESOLUTION
        proc_h = int(orig_h * scale)
    else:
        scale = 1.0
        proc_w, proc_h = orig_w, orig_h

    # Collect unique frame indices we need to seek to
    needed_frames: dict[int, list[int]] = {}  # frame_idx → [tracker_id, ...]
    for tid, row in track_rows.items():
        fidx = int(row["frame_idx"])
        needed_frames.setdefault(fidx, []).append(tid)

    crops: dict[int, tuple] = {}
    for fidx in sorted(needed_frames.keys()):
        cap.set(cv2.CAP_PROP_POS_FRAMES, fidx)
        ret, frame = cap.read()
        if not ret:
            continue
        # Downscale to match the resolution the pipeline processed at
        if scale != 1.0:
            frame = cv2.resize(frame, (proc_w, proc_h))
        for tid in needed_frames[fidx]:
            row = track_rows[tid]
            x1, y1, x2, y2 = int(row["x1"]), int(row["y1"]), int(row["x2"]), int(row["y2"])
            h, w = frame.shape[:2]
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(w, x2), min(h, y2)
            if x2 <= x1 or y2 <= y1:
                continue
            crop_bgr = frame[y1:y2, x1:x2]
            crop_rgb = cv2.cvtColor(
                cv2.resize(crop_bgr, (crop_size, crop_size)), cv2.COLOR_BGR2RGB
            )
            crops[tid] = (crop_rgb, str(row["predicted_label"]), int(row["frame_idx"]))

    cap.release()
    return crops


def load_existing_labels(path: str) -> dict:
    """Load previously saved labels so session survives page reruns."""
    if os.path.exists(path):
        df = pd.read_csv(path)
        if "tracker_id" in df.columns and "true_label" in df.columns:
            return dict(zip(df["tracker_id"].astype(int), df["true_label"]))
    return {}


# ---------------------------------------------------------------------------
# Main UI
# ---------------------------------------------------------------------------

st.title("⚽ Soccer Vision — Track Labeling Tool")
st.caption(
    "Review model predictions per player track. "
    "Correct any wrong labels, then click **Save Labels**."
)

# Validate inputs
if not os.path.exists(args.predictions):
    st.error(
        f"Predictions file not found: `{args.predictions}`\n\n"
        "Run the pipeline with `save_predictions: true` in config.yaml first."
    )
    st.stop()

if not os.path.exists(args.video):
    st.error(f"Video file not found: `{args.video}`")
    st.stop()

# Load data
df_preds = load_predictions(args.predictions)
crops = extract_crops(args.predictions, args.video)

if not crops:
    st.warning("No crops could be extracted. Check that the video matches the predictions CSV.")
    st.stop()

# Load any previously saved labels into session state
if "user_labels" not in st.session_state:
    st.session_state.user_labels = load_existing_labels(args.out)

# Sidebar stats
st.sidebar.header("Statistics")
st.sidebar.metric("Total tracks", len(crops))
pred_counts = df_preds["predicted_label"].value_counts()
for label in LABELS:
    st.sidebar.metric(f"Predicted {label}", int(pred_counts.get(label, 0)))

st.sidebar.markdown("---")
st.sidebar.markdown(
    "**Instructions**\n"
    "1. Each card shows one player track crop\n"
    "2. The selectbox is pre-filled with the model's prediction\n"
    "3. Correct any wrong labels\n"
    "4. Click **Save Labels** when done"
)

# Grid layout — 5 columns
COLS = 5
track_ids = sorted(crops.keys())
st.subheader(f"Player Tracks ({len(track_ids)} total)")

for row_start in range(0, len(track_ids), COLS):
    cols = st.columns(COLS)
    for col_idx, tid in enumerate(track_ids[row_start: row_start + COLS]):
        crop_rgb, predicted, frame_idx = crops[tid]
        with cols[col_idx]:
            st.image(crop_rgb, use_container_width=True)
            st.caption(f"Track #{tid} · frame {frame_idx}")
            default_label = st.session_state.user_labels.get(tid, predicted)
            default_idx = LABELS.index(default_label) if default_label in LABELS else 0
            chosen = st.selectbox(
                f"Label ##{tid}",
                options=LABELS,
                index=default_idx,
                key=f"label_{tid}",
                label_visibility="collapsed",
            )
            st.session_state.user_labels[tid] = chosen

# Save button
st.markdown("---")
col_save, col_status = st.columns([1, 3])
with col_save:
    if st.button("💾 Save Labels", type="primary", use_container_width=True):
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        rows = [
            {"tracker_id": tid, "true_label": st.session_state.user_labels[tid]}
            for tid in sorted(st.session_state.user_labels.keys())
        ]
        pd.DataFrame(rows).to_csv(out_path, index=False)
        with col_status:
            st.success(f"Saved {len(rows)} track labels → `{out_path}`")

# Quick accuracy preview
if os.path.exists(args.out):
    gt_df = pd.read_csv(args.out)
    if len(gt_df) > 0:
        st.markdown("---")
        st.subheader("Quick Accuracy Preview")
        merged = df_preds.merge(gt_df, on="tracker_id", how="inner")
        if len(merged) > 0:
            # Per-track: majority vote prediction vs true label
            track_acc = (
                merged.groupby("tracker_id")
                .apply(
                    lambda g: g["predicted_label"].mode()[0] == g["true_label"].iloc[0],
                    include_groups=False,
                )
                .mean()
            )
            st.metric("Per-track accuracy (labeled tracks)", f"{track_acc:.1%}")
            st.caption(
                "Run `python scripts/evaluate.py` for the full metric report "
                "including flip rate and confusion matrix."
            )
